from app.schemas.auth import *
from app.schemas.user import *
from app.schemas.settings import *
from app.schemas.interest import *
from app.schemas.prompt import *
from app.schemas.photo import *
from app.schemas.swipe import *
from app.schemas.match import *
from app.schemas.message import *
from app.schemas.subscription import *
from app.schemas.report import *
from app.schemas.rewards import *
from app.schemas.referral import *
from app.schemas.notification import *
from app.schemas.ticket import *
from app.schemas.location import *
from app.schemas.admin import *
from app.schemas.discover import *
from app.schemas.search import *
from app.schemas.dashboard import *